name: 'ad_reporting'
version: '1.0.0'
config-version: 2

profile: 'default'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

vars:
  ad_reporting__pinterest_enabled: true
  ad_reporting__microsoft_ads_enabled: true
  ad_reporting__linkedin_ads_enabled: true
  ad_reporting__google_ads_enabled: true
  ad_reporting__twitter_ads_enabled: true
  ad_reporting__facebook_ads_enabled: true

models:
  ad_reporting:
    +materialized: table
